services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compagnie
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    restart: unless-stopped

  springboot-app:
    container_name: springboot-app
    build: .
    ports:
      - "9091:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/compagnie?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mariadb
    restart: unless-stopped

  react-app:
    build: ./src/main/webapp/reactjs
    container_name: react-app
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:9091
    depends_on:
      - springboot-app
    restart: unless-stopped