version: "3"

services:
  springboot-app:
    image: springboot-app
    build: .
    restart: always
    ports:
      - "9090:8082"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: miola
      MYSQL_ROOT_PASSWORD: root
