# my global config
global:
  scrape_interval: 15s  # Intervalle de collecte par défaut
  evaluation_interval: 15s  # Intervalle d'évaluation des règles

# Fichiers de règles (commentés car non utilisés pour l'instant)
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# Configuration des cibles à surveiller
scrape_configs:
  # Job pour surveiller Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:7070']

  # Job pour surveiller l'application Spring Boot
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s  # Collecte plus fréquente pour l'application
    static_configs:
      - targets: ['host.docker.internal:8081']